import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundImage;
import javafx.scene.layout.BackgroundPosition;
import javafx.scene.layout.BackgroundRepeat;
import javafx.scene.layout.BackgroundSize;
import javafx.stage.Stage;

/**
 * defines a space trader game
 */
public class SpaceTrader extends Application {

    private static final int WINDOW_WIDTH = 640;
    private static final int WINDOW_HEIGHT = 640;
    public static final Background BACKGROUND = new Background(new BackgroundImage(
            new Image("assets/background.jpg", 680, 520, false, true), BackgroundRepeat.REPEAT,
            null, BackgroundPosition.DEFAULT, BackgroundSize.DEFAULT));

    /**
    * start method provided by JavaFX
    * @param primaryStage the stage generated by JavaFX
    */
    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Space Trader");
        primaryStage.setResizable(false);

        MainMenu mainMenu = new MainMenu(primaryStage);
        Scene scene = new Scene(mainMenu, WINDOW_WIDTH, WINDOW_HEIGHT);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    /**
     * main method
     * @param args default
     */
    public static void main(String[] args) {
        Music.playMusic("src/assets/music.wav");
        launch(args);
    }

}
